### Nine lives

In [1]:
import random
lives =9
heart_symbol='\u2764'
words=["hello","pizza","apple","fairy","teeth"]
secret_word=random.choice(words)
clue=list('?????')
gussed_word_correctly=False

In [3]:
def update_clue(guessed_letter,secret_word,clue):
    index=0
    while index<len(secret_word):
        if guessed_letter==secret_word[index]:
            clue[index]=guessed_letter
        index +=1

In [5]:

while lives>0:
    print(clue)
    print("lives left:",heart_symbol*lives)
    guess=input("Guess a letter or whole word")
    if guess==secret_word:
        guessed_word_correctly=True
        break
    elif guess in secret_word:
        update_clue(guess,secret_word,clue)
    else:
        print("Incorrect gues.you lose a life")
        lives -= 1
    if guessed_word_correctly==True:
        print("you won the game,secret_word was:",secret_word)
    else:
        print("you lost the game,secret_word was:",secret_word)

['?', '?', '?', '?', '?']
lives left: ❤❤❤❤❤❤❤❤
Guess a letter or whole worda
Incorrect gues.you lose a life


NameError: name 'guessed_word_correctly' is not defined

### Numpy Packages:

In [6]:

import numpy as np

In [7]:
#1-dimensional array
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [8]:
#2-dimensional array
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
a1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
a1.ndim

2

In [10]:
a1.shape

(3, 3)

In [11]:
a.shape

(5,)

In [12]:
a2=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a2.shape[0])
print(a2.shape[1])

4
3


In [13]:
#inserting elemnets into the array dynamically
a3=np.array([],dtype="int32")

In [14]:
a3=np.append(a3,int(input()))
a3

12


array([12])

In [15]:

a3=np.append(a3,[23,34,45,56,67])
a3

array([12, 23, 34, 45, 56, 67])

In [16]:
a2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])


### slicing

In [17]:
print(a3[3])

45


In [18]:

print(a2[1,1])

5


In [19]:

print(a2[2:,:])

[[ 7  8  9]
 [10 11 12]]


In [20]:
print(a2[2:,0:])

[[ 7  8  9]
 [10 11 12]]


In [21]:
print(a2[0,0:2])

[1 2]


In [22]:

print(a2[0::2,:])

[[1 2 3]
 [7 8 9]]



### iterate through array¶

In [23]:
for row in a2:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [24]:
list1=[[1,2],[3,4]]
for i in list1:
    print(i)

[1, 2]
[3, 4]


In [25]:
for ele in a2.flat:
    print(ele,end=" ")

1 2 3 4 5 6 7 8 9 10 11 12 

In [26]:
np.array(a2.flat)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])


### Indexing with boolen array

In [27]:
arr1=np.arange(1,21).reshape(5,4)
arr1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [28]:
result=(arr1 % 2==0)
result

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [29]:
arr1[result]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])


### Appending array:

In [7]:
arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(11,20).reshape(3,3)
print(np.vstack((arr1,arr2)))

NameError: name 'np' is not defined

In [3]:
print(np.vstack((arr1,arr2)))

NameError: name 'np' is not defined

In [4]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(11,20).reshape(3,3)
print(np.vstack((arr1,arr2)))  ## vertical stacking

NameError: name 'np' is not defined

In [5]:
print(np.hstack((arr1,arr2))) ## horizontal stacking

NameError: name 'np' is not defined


### Attributes:
size
itemsize
dtype
ndim
shape

In [6]:
arr=np.arange(1,11).reshape(2,5)
arr

NameError: name 'np' is not defined

In [8]:

print(arr.size)
print(arr.itemsize)
print(arr.dtype)
print(arr.ndim)
print(arr.shape)

NameError: name 'arr' is not defined


### Functions:
zeros
ones
full

In [9]:

z=np.zeros((2,3),dtype="int32")
z

NameError: name 'np' is not defined

In [10]:

o=np.ones((3,3),dtype="int32")
o

NameError: name 'np' is not defined

In [11]:
f=np.full((2,2),"aashrith")
print(f)

NameError: name 'np' is not defined

In [12]:
#eye()
e=np.eye(3,dtype="int32")
e

NameError: name 'np' is not defined

In [13]:

#linspace()-->linear spacing elements
l=np.linspace(1,10,5)
l

NameError: name 'np' is not defined

In [14]:

a=np.arange(1,13,2)#range(start,stop,step)
a

NameError: name 'np' is not defined

In [15]:
a=a.reshape(2,3)
a

NameError: name 'a' is not defined

In [16]:
#ravel()
print(np.array(a.flat))
print(a.ravel())

NameError: name 'np' is not defined


### Function:
min()
max()
sum()
sqrt()
mean()
median()
std()

In [17]:

print(a.min())
print(a.max())

NameError: name 'a' is not defined

In [18]:

a

NameError: name 'a' is not defined

In [1]:
print(a.sum())#sum of all elements
print(a.sum(axis=1))#sum of row elements
print(a.sum(axis=0))#sum of coloumn elements

NameError: name 'a' is not defined

In [2]:
np.sqrt(a)


NameError: name 'np' is not defined

In [3]:

np.mean(a)

NameError: name 'np' is not defined

In [4]:
np.median(a)

NameError: name 'np' is not defined

In [5]:

np.std(a)

NameError: name 'np' is not defined


### Mathematical Operations:+,-,*,/,%

In [6]:
arr1=np.arange(1,11)
arr2=np.arange(11,21)
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)
print(arr1%arr2)

NameError: name 'np' is not defined


### dot()-->Matrix multiplication
### arr1=m X n
### arr2=n X l

In [7]:

arr1=np.arange(1,10).reshape(3,3)
arr2=np.arange(11,20).reshape(3,3)
arr1.dot(arr2)

NameError: name 'np' is not defined

In [8]:

arr1

NameError: name 'arr1' is not defined

In [9]:
#Transpose of an array
arr1.T

NameError: name 'arr1' is not defined


### Applying user-defined function:

In [10]:
list1=list(range(1,20))
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [11]:

a=np.array(list1)
a

NameError: name 'np' is not defined

In [12]:
#1/(1+1)-->x/(x+1)
result=[x/(x+1) for x in list1]
result

[0.5,
 0.6666666666666666,
 0.75,
 0.8,
 0.8333333333333334,
 0.8571428571428571,
 0.875,
 0.8888888888888888,
 0.9,
 0.9090909090909091,
 0.9166666666666666,
 0.9230769230769231,
 0.9285714285714286,
 0.9333333333333333,
 0.9375,
 0.9411764705882353,
 0.9444444444444444,
 0.9473684210526315,
 0.95]

In [13]:
f=np.vectorize(lambda x : x/(x+1))
f(a)

NameError: name 'np' is not defined

In [14]:
help(np.linlag)

NameError: name 'np' is not defined