In [1]:
from numpy import random
print(random.randint(1,100))#random integer in the given range
print(random.rand())#float number 0-1

52
0.7411416513169726


In [2]:
#creating n dimensional array with random values
print(random.randint(100,size=(3)))
print(random.randint(100,size=(3,4)))
print(random.randint(100,size=(3,4,2)))

[15 91 67]
[[58 93 64 77]
 [19 96 13 36]
 [28 51 95 25]]
[[[24 13]
  [75 85]
  [28 81]
  [97 77]]

 [[69 27]
  [ 0 49]
  [94 19]
  [51 61]]

 [[ 8 30]
  [ 2 55]
  [11 80]
  [90 62]]]


In [3]:
#creating n dimensional array with random floating point values
print(random.rand())
print(random.rand(3))
print(random.rand(2,3))

0.91977077049658
[0.03297378 0.18828718 0.85026897]
[[0.7425508  0.97838633 0.10192807]
 [0.49924986 0.30261977 0.6191245 ]]


In [4]:
a= random.randint(100,size=(3)).ravel()
a

array([29, 38,  0])

In [5]:
random.choice(a)

38

In [6]:
#for generating an array with the given shape and elements from the given list
random.choice([1,2,3,4,5],size=(3,4))

array([[4, 4, 3, 1],
       [5, 3, 2, 5],
       [1, 5, 4, 3]])

### Creating a DataFrame
using 2 directories

In [8]:
import pandas as pd
import numpy as np
dict1={'a':1,'b':2,'c':3,'d':4,'e':5}
dict2={'a':5,'b':6,'c':7,'d':8,'e':9}
data={"First":dict1,"Second":dict2}
df=pd.DataFrame(data)
df

First  Second
a      1       5
b      2       6
c      3       7
d      4       8
e      5       9

In [9]:
# simple dicionary-->dataframe
d1 = {"name":["nihith","nani","pichi"],"address":["hyd","wgl","goa"]}
df1 = pd.DataFrame(d1)
df1

name address
0  nihith     hyd
1    nani     wgl
2   pichi     goa

In [10]:
# using series
s1 = pd.Series([1,2,3,4,5,6,7,8,9,10])
s2 = pd.Series([11.1,12.2,13.3,14.4,15.5,16.6,17.7,18.8,19.0,20.0])
s3 = pd.Series(['a','b','c','d','e','f','g','h','i','j'])
data = {"a":s1,"musko":s2,"ra":s3}
df3 = pd.DataFrame(data)
df3

a  musko ra
0   1   11.1  a
1   2   12.2  b
2   3   13.3  c
3   4   14.4  d
4   5   15.5  e
5   6   16.6  f
6   7   17.7  g
7   8   18.8  h
8   9   19.0  i
9  10   20.0  j

### selecting the data from the data frame
loc
iloc

In [11]:
s4["marks"]

NameError: name 's4' is not defined

In [12]:
s4[["studentno","marks"]]

NameError: name 's4' is not defined

In [13]:
s4.loc[:,"studentno"]

NameError: name 's4' is not defined

In [14]:
# single colum
df3.loc[:,"a"]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: a, dtype: int64

In [15]:
df3.loc[0:5,["a","aa"]]

C:\Users\MOHIT\Anaconda3\lib\site-packages\pandas\core\indexing.py:1494: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)


a  aa
0  1 NaN
1  2 NaN
2  3 NaN
3  4 NaN
4  5 NaN
5  6 NaN

In [16]:
df3.iloc[:,0]

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: a, dtype: int64

In [17]:
df3.iloc[0:4,0:1]

a
0  1
1  2
2  3
3  4